### ISSUE TITLE
Fails to run on OSX

### ISSUE THREAD

**Issue by dblock** [igrigorik/em-http-request#298]
I've spent a fair amount of time trying to make this work :(

Using Faraday's `adapter :em_http` on OSX.

```
19:10:16 console.1 | /Users/dblock/.rvm/gems/ruby-2.3.0/gems/eventmachine-1.2.0.1/lib/em/connection.rb:430:in `block in start_tls': Could not find /System/Library/OpenSSL (EventMachine::FileNotFoundException)
19:10:16 console.1 | /ca-certificates.crt for start_tls
19:10:16 console.1 | 	from /Users/dblock/.rvm/gems/ruby-2.3.0/gems/eventmachine-1.2.0.1/lib/em/connection.rb:428:in `each'
19:10:16 console.1 | 	from /Users/dblock/.rvm/gems/ruby-2.3.0/gems/eventmachine-1.2.0.1/lib/em/connection.rb:428:in `start_tls'
19:10:16 console.1 | 	from /Users/dblock/.rvm/gems/ruby-2.3.0/gems/em-http-request-1.1.3/lib/em-http/http_connection.rb:172:in `start'
19:10:16 console.1 | 	from /Users/dblock/.rvm/gems/ruby-2.3.0/gems/em-http-request-1.1.3/lib/em-http/http_connection.rb:167:in `connection_completed'
19:10:16 console.1 | 	from /Users/dblock/.rvm/gems/ruby-2.3.0/gems/em-http-request-1.1.3/lib/em-http/http_connection.rb:27:in `connection_completed'
19:10:16 console.1 | 	from /Users/dblock/.rvm/gems/ruby-2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
19:10:16 console.1 | 	from /Users/dblock/.rvm/gems/ruby-2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
19:10:16 console.1 | 	from /Users/dblock/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/em_http.rb:105:in `perform_request'
19:10:16 console.1 | 	from /Users/dblock/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/em_http.rb:90:in `call'
19:10:16 console.1 | 	from /Users/dblock/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
19:10:16 console.1 | 	from /Users/dblock/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/response/logger.rb:24:in `call'
19:10:16 console.1 | 	from /Users/dblock/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
19:10:16 console.1 | 	from /Users/dblock/.rvm/gems/ruby-2.3.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
19:10:16 console.1 | 	from /Users/dblock/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
19:10:16 console.1 | 	from /Users/dblock/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
19:10:16 console.1 | 	from /Users/dblock/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
19:10:16 console.1 | 	from /Users/dblock/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/request/multipart.rb:14:in `call'
19:10:16 console.1 | 	from /Users/dblock/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
19:10:16 console.1 | 	from /Users/dblock/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
19:10:16 console.1 | 	from /Users/dblock/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
...
```

**Comment by igrigorik** [comment]
You need to rebuild EM, see: https://github.com/eventmachine/eventmachine/issues/602

**Comment by dblock** [comment]
@igrigorik I did that, but same problem. It's not finding `ca-certificates.crt`, which I have no idea where it's supposed to come from :(

**Comment by igrigorik** [comment]
Maybe this can help: https://gist.github.com/1stvamp/2158128
